### PR TITLE
Request to incorporate changes into the project

### PR DESCRIPTION
**Pull request by Supershade2**
I would like to ask for feedback and if possible integration of support for MegaSurvivorPack by SirQuacker.

### CODE REVIEW

**Comment by niwith** [comment]
Sorry @Supershade2 only just saw the pull request, I'll take a look at it

**Comment by Supershade2** [comment]
> Sorry @Supershade2 only just saw the pull request, I'll take a look at it

It's alright I'm glad you got back to me and I look forward to talking with you :)

**Comment by niwith** [comment]
@Supershade2 check out the latest version of the mod thunderstore, is it now working with the characters you were trying with?

**Comment by Supershade2** [comment]
Let me give it a shot

**Comment by Supershade2** [comment]
> @Supershade2 check out the latest version of the mod thunderstore, is it now working with the characters you were trying with?

It works, thank you very much for your work and thank you for taking time out to address this! 👍

**Comment by Supershade2** [comment]
I'll close this request now

**Pull request closed without merging**
